#spring:
#  datasource:
#    url: "jdbc:postgresql://localhost:5433/pdpmigration?currentSchema=sb_flyway"
#    username: postgres
#    password: 123
#    driver-class-name: org.postgresql.Driver
#
#  flyway:
#    enabled: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pdpmigration?currentSchema=sb_liquibase
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true

#  flyway:
#    enabled: true
#    locations: classpath:db_migration

